# Generated by Django 2.0 on 2019-04-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subinfo', '0002_auto_20190405_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl1',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl2',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl3',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl4',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl5',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='contenttableinfo',
            name='tl6',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
