# Generated by Django 2.0 on 2019-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subinfo', '0003_auto_20190405_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelementimage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
